// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TMS.API;

#nullable disable

namespace TMS.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220518114238_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CourseUser", b =>
                {
                    b.Property<int>("CoursesId")
                        .HasColumnType("int");

                    b.Property<int>("UsersId")
                        .HasColumnType("int");

                    b.HasKey("CoursesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("CourseUser");

                    b.HasData(
                        new
                        {
                            CoursesId = 1,
                            UsersId = 12
                        },
                        new
                        {
                            CoursesId = 1,
                            UsersId = 13
                        },
                        new
                        {
                            CoursesId = 1,
                            UsersId = 14
                        },
                        new
                        {
                            CoursesId = 1,
                            UsersId = 8
                        },
                        new
                        {
                            CoursesId = 2,
                            UsersId = 16
                        },
                        new
                        {
                            CoursesId = 2,
                            UsersId = 17
                        },
                        new
                        {
                            CoursesId = 2,
                            UsersId = 7
                        });
                });

            modelBuilder.Entity("TMS.BAL.Assignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Base64")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("Document")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("StatusId");

                    b.HasIndex("TopicId");

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("TMS.BAL.AssignmentStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("AssignmentStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2022, 5, 18, 11, 42, 36, 356, DateTimeKind.Utc).AddTicks(6686),
                            Status = "Submitted"
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2022, 5, 18, 11, 42, 36, 356, DateTimeKind.Utc).AddTicks(6686),
                            Status = "Yet to be Submitted"
                        });
                });

            modelBuilder.Entity("TMS.BAL.Attendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("StatusId");

                    b.HasIndex("TopicId");

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("TMS.BAL.AttendanceStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("AttendanceStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2022, 5, 18, 11, 42, 36, 356, DateTimeKind.Utc).AddTicks(6686),
                            Status = "Present"
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2022, 5, 18, 11, 42, 36, 356, DateTimeKind.Utc).AddTicks(6686),
                            Status = "Absent"
                        });
                });

            modelBuilder.Entity("TMS.BAL.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StatusId")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("isDisabled")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("StatusId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2022, 5, 18, 11, 42, 36, 356, DateTimeKind.Utc).AddTicks(6686),
                            DepartmentId = 3,
                            Description = "You can launch a new career in web development today by learning HTML & CSS. You don't need a computer science degree or expensive software. All you need is a computer, a bit of time, a lot of determination, and a teacher you trust. I've taught HTML and CSS to countless coworkers and held training sessions for fortune 100 companies. I am that teacher you can trust.",
                            Duration = "11 hrs",
                            Name = "HTML 5 With CSS 3",
                            isDisabled = false
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2022, 5, 18, 11, 42, 36, 356, DateTimeKind.Utc).AddTicks(6686),
                            DepartmentId = 3,
                            Description = "You can launch a new career by learning SQL RDBMS. You don't need a computer science degree or expensive software. All you need is a computer, a bit of time, a lot of determination, and a teacher you trust. I've taught RDBMS to countless coworkers and held training sessions for fortune 100 companies. I am that teacher you can trust.",
                            Duration = "28 hrs",
                            Name = "SQL RDBMS",
                            isDisabled = false
                        });
                });

            modelBuilder.Entity("TMS.BAL.CourseFeedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Feedback")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<float>("Rating")
                        .HasColumnType("real");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("OwnerId");

                    b.ToTable("CourseFeedbacks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            CreatedOn = new DateTime(2022, 5, 18, 11, 42, 36, 356, DateTimeKind.Utc).AddTicks(6686),
                            Feedback = "Enim lobortis scelerisque fermentum dui faucibus in ornare quam viverra. Dui vivamus arcu felis bibendum ut. Enim blandit volutpat maecenas volutpat",
                            OwnerId = 13,
                            Rating = 3.8f
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 2,
                            CreatedOn = new DateTime(2022, 5, 18, 11, 42, 36, 356, DateTimeKind.Utc).AddTicks(6686),
                            Feedback = " Enim lobortis scelerisque fermentum dui faucibus in ornare quam viverra. Dui vivamus arcu felis bibendum ut. Enim blandit volutpat maecenas volutpat",
                            OwnerId = 17,
                            Rating = 4.3f
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 1,
                            CreatedOn = new DateTime(2022, 5, 18, 11, 42, 36, 356, DateTimeKind.Utc).AddTicks(6686),
                            Feedback = "Enim lobortis scelerisque fermentum dui faucibus in ornare quam viverra. Dui vivamus arcu felis bibendum ut. Enim blandit volutpat maecenas volutpat",
                            OwnerId = 12,
                            Rating = 4.8f
                        },
                        new
                        {
                            Id = 4,
                            CourseId = 2,
                            CreatedOn = new DateTime(2022, 5, 18, 11, 42, 36, 356, DateTimeKind.Utc).AddTicks(6686),
                            Feedback = " Enim lobortis scelerisque fermentum dui faucibus in ornare quam viverra. Dui vivamus arcu felis bibendum ut. Enim blandit volutpat maecenas volutpat",
                            OwnerId = 16,
                            Rating = 3.6f
                        });
                });

            modelBuilder.Entity("TMS.BAL.CourseStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("CourseStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2022, 5, 18, 11, 42, 36, 356, DateTimeKind.Utc).AddTicks(6686),
                            Status = "Completed"
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2022, 5, 18, 11, 42, 36, 356, DateTimeKind.Utc).AddTicks(6686),
                            Status = "In Progress"
                        });
                });

            modelBuilder.Entity("TMS.BAL.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("isDisabled")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2022, 5, 18, 11, 42, 36, 356, DateTimeKind.Utc).AddTicks(6686),
                            Name = ".NET",
                            isDisabled = false
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2022, 5, 18, 11, 42, 36, 356, DateTimeKind.Utc).AddTicks(6686),
                            Name = "JAVA",
                            isDisabled = false
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2022, 5, 18, 11, 42, 36, 356, DateTimeKind.Utc).AddTicks(6686),
                            Name = "LAMP",
                            isDisabled = false
                        });
                });

            modelBuilder.Entity("TMS.BAL.MOM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Agenda")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("MeetingNotes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<string>("PurposeOfMeeting")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReviewId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("ReviewId");

                    b.HasIndex("StatusId");

                    b.ToTable("MOMs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Agenda = "Lorem ipsum dolor sit amet\nAdipiscing elit duis\nAenean euismod elementum",
                            CreatedOn = new DateTime(2022, 5, 18, 11, 42, 36, 356, DateTimeKind.Utc).AddTicks(6686),
                            MeetingNotes = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dolor purus non enim praesent elementum facilisis. Nisi scelerisque eu ultrices vitae auctor eu augue ut lectus. Adipiscing elit duis tristique sollicitudin nibh sit amet. Id eu nisl nunc mi ipsum faucibus vitae aliquet. Cras ornare arcu dui vivamus arcu felis bibendum ut tristique. Enim lobortis scelerisque fermentum dui faucibus in ornare quam viverra. Dui vivamus arcu felis bibendum ut. Enim blandit volutpat maecenas volutpat. Ut ornare lectus sit amet est placerat in egestas erat. Dictumst quisque sagittis purus sit amet volutpat consequat mauris nunc. Aenean euismod elementum nisi quis eleifend quam adipiscing vitae. Ac auctor augue mauris augue. Sagittis orci a scelerisque purus semper eget. Massa placerat duis ultricies lacus sed turpis.",
                            OwnerId = 13,
                            PurposeOfMeeting = "Eu consequat ac felis donec et odio pellentesque diam volutpat. Suspendisse in est ante in. Dis parturient montes nascetur ridiculus mus mauris vitae ultricies leo. Leo vel orci porta non pulvinar neque. Ultrices vitae auctor eu augue ut lectus arcu. Nec sagittis aliquam malesuada bibendum arcu vitae elementum curabitur vitae. Quisque sagittis purus sit amet volutpat. Semper feugiat nibh sed pulvinar proin gravida hendrerit lectus a.",
                            ReviewId = 1,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 2,
                            Agenda = "Lorem ipsum dolor sit amet\nAdipiscing elit duis\nAenean euismod elementum",
                            CreatedOn = new DateTime(2022, 5, 18, 11, 42, 36, 356, DateTimeKind.Utc).AddTicks(6686),
                            MeetingNotes = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dolor purus non enim praesent elementum facilisis. Nisi scelerisque eu ultrices vitae auctor eu augue ut lectus. Adipiscing elit duis tristique sollicitudin nibh sit amet. Id eu nisl nunc mi ipsum faucibus vitae aliquet. Cras ornare arcu dui vivamus arcu felis bibendum ut tristique. Enim lobortis scelerisque fermentum dui faucibus in ornare quam viverra. Dui vivamus arcu felis bibendum ut. Enim blandit volutpat maecenas volutpat. Ut ornare lectus sit amet est placerat in egestas erat. Dictumst quisque sagittis purus sit amet volutpat consequat mauris nunc. Aenean euismod elementum nisi quis eleifend quam adipiscing vitae. Ac auctor augue mauris augue. Sagittis orci a scelerisque purus semper eget. Massa placerat duis ultricies lacus sed turpis.",
                            OwnerId = 13,
                            PurposeOfMeeting = "Eu consequat ac felis donec et odio pellentesque diam volutpat. Suspendisse in est ante in. Dis parturient montes nascetur ridiculus mus mauris vitae ultricies leo. Leo vel orci porta non pulvinar neque. Ultrices vitae auctor eu augue ut lectus arcu. Nec sagittis aliquam malesuada bibendum arcu vitae elementum curabitur vitae. Quisque sagittis purus sit amet volutpat. Semper feugiat nibh sed pulvinar proin gravida hendrerit lectus a.",
                            ReviewId = 4,
                            StatusId = 1
                        });
                });

            modelBuilder.Entity("TMS.BAL.MOMStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("MOMStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2022, 5, 18, 11, 42, 36, 356, DateTimeKind.Utc).AddTicks(6686),
                            Status = "Submitted"
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2022, 5, 18, 11, 42, 36, 356, DateTimeKind.Utc).AddTicks(6686),
                            Status = "Yet to be Submitted"
                        });
                });

            modelBuilder.Entity("TMS.BAL.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReviewDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReviewTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReviewerId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<int>("TraineeId")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("isDisabled")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ReviewerId");

                    b.HasIndex("StatusId");

                    b.HasIndex("TraineeId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2022, 5, 18, 11, 42, 36, 356, DateTimeKind.Utc).AddTicks(6686),
                            Mode = "online",
                            ReviewDate = "18-05-2022",
                            ReviewTime = "17:12:36.3571750",
                            ReviewerId = 11,
                            StatusId = 1,
                            TraineeId = 13,
                            isDisabled = false
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2022, 5, 18, 11, 42, 36, 356, DateTimeKind.Utc).AddTicks(6686),
                            Mode = "Offline",
                            ReviewDate = "18-05-2022",
                            ReviewTime = "17:12:36.3571849",
                            ReviewerId = 11,
                            StatusId = 2,
                            TraineeId = 15,
                            isDisabled = false
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2022, 5, 18, 11, 42, 36, 356, DateTimeKind.Utc).AddTicks(6686),
                            Mode = "online",
                            ReviewDate = "18-05-2022",
                            ReviewTime = "17:12:36.3571902",
                            ReviewerId = 11,
                            StatusId = 3,
                            TraineeId = 16,
                            isDisabled = false
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(2022, 5, 18, 11, 42, 36, 356, DateTimeKind.Utc).AddTicks(6686),
                            Mode = "online",
                            ReviewDate = "18-05-2022",
                            ReviewTime = "17:12:36.3571928",
                            ReviewerId = 10,
                            StatusId = 1,
                            TraineeId = 12,
                            isDisabled = false
                        },
                        new
                        {
                            Id = 5,
                            CreatedOn = new DateTime(2022, 5, 18, 11, 42, 36, 356, DateTimeKind.Utc).AddTicks(6686),
                            Mode = "Offline",
                            ReviewDate = "18-05-2022",
                            ReviewTime = "17:12:36.3571951",
                            ReviewerId = 9,
                            StatusId = 2,
                            TraineeId = 12,
                            isDisabled = false
                        },
                        new
                        {
                            Id = 6,
                            CreatedOn = new DateTime(2022, 5, 18, 11, 42, 36, 356, DateTimeKind.Utc).AddTicks(6686),
                            Mode = "online",
                            ReviewDate = "18-05-2022",
                            ReviewTime = "17:12:36.3571973",
                            ReviewerId = 10,
                            StatusId = 3,
                            TraineeId = 17,
                            isDisabled = false
                        });
                });

            modelBuilder.Entity("TMS.BAL.ReviewStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ReviewStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2022, 5, 18, 11, 42, 36, 356, DateTimeKind.Utc).AddTicks(6686),
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2022, 5, 18, 11, 42, 36, 356, DateTimeKind.Utc).AddTicks(6686),
                            Status = "Upcoming"
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2022, 5, 18, 11, 42, 36, 356, DateTimeKind.Utc).AddTicks(6686),
                            Status = "Canceled"
                        });
                });

            modelBuilder.Entity("TMS.BAL.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("isDisabled")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2022, 5, 18, 11, 42, 36, 356, DateTimeKind.Utc).AddTicks(6686),
                            Name = "Training Head",
                            isDisabled = false
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2022, 5, 18, 11, 42, 36, 356, DateTimeKind.Utc).AddTicks(6686),
                            Name = "Co Ordinator",
                            isDisabled = false
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2022, 5, 18, 11, 42, 36, 356, DateTimeKind.Utc).AddTicks(6686),
                            Name = "Trainer",
                            isDisabled = false
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(2022, 5, 18, 11, 42, 36, 356, DateTimeKind.Utc).AddTicks(6686),
                            Name = "Trainee",
                            isDisabled = false
                        },
                        new
                        {
                            Id = 5,
                            CreatedOn = new DateTime(2022, 5, 18, 11, 42, 36, 356, DateTimeKind.Utc).AddTicks(6686),
                            Name = "Reviewer",
                            isDisabled = false
                        });
                });

            modelBuilder.Entity("TMS.BAL.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("isDisabled")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Topics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "All HTML documents must start with a document type declaration: <!DOCTYPE html>. \nThe HTML document itself begins with < html > and ends with </ html >.\nThe visible part of the HTML document is between<> and </ body >.\n HTML headings are defined with the <h1> to <h6> tags. \n< h1 > defines the most important heading. < h6 > defines the least important heading: \nHTML paragraphs are defined with the <p> tag \n HTML links are defined with the <a> tag \nHTML images are defined with the <img> tag.\nThe source file(src), alternative text(alt),width,and height are provided as attributes",
                            CourseId = 1,
                            CreatedOn = new DateTime(2022, 5, 18, 11, 42, 36, 356, DateTimeKind.Utc).AddTicks(6686),
                            Duration = "50 mins",
                            Name = "HTML Basics",
                            isDisabled = false
                        },
                        new
                        {
                            Id = 2,
                            Content = "All HTML documents must start with a document type declaration: <!DOCTYPE html>. \nThe HTML document itself begins with < html > and ends with </ html >.\nThe visible part of the HTML document is between<> and </ body >.\n HTML headings are defined with the <h1> to <h6> tags. \n< h1 > defines the most important heading. < h6 > defines the least important heading: \nHTML paragraphs are defined with the <p> tag \n HTML links are defined with the <a> tag \nHTML images are defined with the <img> tag.\nThe source file(src), alternative text(alt),width,and height are provided as attributes",
                            CourseId = 1,
                            CreatedOn = new DateTime(2022, 5, 18, 11, 42, 36, 356, DateTimeKind.Utc).AddTicks(6686),
                            Duration = "50 mins",
                            Name = "CSS Basics",
                            isDisabled = false
                        },
                        new
                        {
                            Id = 3,
                            Content = "All HTML documents must start with a document type declaration: <!DOCTYPE html>. \nThe HTML document itself begins with < html > and ends with </ html >.\nThe visible part of the HTML document is between<> and </ body >.\n HTML headings are defined with the <h1> to <h6> tags. \n< h1 > defines the most important heading. < h6 > defines the least important heading: \nHTML paragraphs are defined with the <p> tag \n HTML links are defined with the <a> tag \nHTML images are defined with the <img> tag.\nThe source file(src), alternative text(alt),width,and height are provided as attributes",
                            CourseId = 1,
                            CreatedOn = new DateTime(2022, 5, 18, 11, 42, 36, 356, DateTimeKind.Utc).AddTicks(6686),
                            Duration = "50 mins",
                            Name = "HTML & CSS Together",
                            isDisabled = false
                        },
                        new
                        {
                            Id = 4,
                            Content = "RDBMS stands for Relational DataBase Management Systems. It is basically a program that allows us to create, delete, and update a relational database. Relational Database is a database system that stores and retrieves data in a tabular format organized in the form of rows and columns.It is a smaller subset of DBMS which was designed by E.F Codd in the 1970s. The major DBMS like SQL, My-SQL, ORACLE are all based on the principles of relational DBMS",
                            CourseId = 2,
                            CreatedOn = new DateTime(2022, 5, 18, 11, 42, 36, 356, DateTimeKind.Utc).AddTicks(6686),
                            Duration = "50 mins",
                            Name = "RDBMS Basics",
                            isDisabled = false
                        },
                        new
                        {
                            Id = 5,
                            Content = "DBMS is the management of data that should remain integrated when any changes are done in it. It is because if the integrity of the data is affected, whole data will get disturbed and corrupted. Therefore, to maintain the integrity of the data, there are four properties described in the database management system, which are known as the ACID properties. The ACID properties are meant for the transaction that goes through a different group of tasks, and there we come to see the role of the ACID properties.\nIn this section, we will learn and understand about the ACID properties. We will learn what these properties stand for and what does each property is used for. We will also understand the ACID properties with the help of some examples.",
                            CourseId = 2,
                            CreatedOn = new DateTime(2022, 5, 18, 11, 42, 36, 356, DateTimeKind.Utc).AddTicks(6686),
                            Duration = "50 mins",
                            Name = "ACID Property",
                            isDisabled = false
                        });
                });

            modelBuilder.Entity("TMS.BAL.TraineeFeedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Feedback")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StatusId")
                        .HasColumnType("int");

                    b.Property<int>("TraineeId")
                        .HasColumnType("int");

                    b.Property<int>("TrainerId")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("isDisabled")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("StatusId");

                    b.HasIndex("TraineeId");

                    b.HasIndex("TrainerId");

                    b.ToTable("TraineeFeedbacks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            CreatedOn = new DateTime(2022, 5, 18, 11, 42, 36, 356, DateTimeKind.Utc).AddTicks(6686),
                            Feedback = "Enim lobortis scelerisque fermentum dui faucibus in ornare quam viverra. Dui vivamus arcu felis bibendum ut. Enim blandit volutpat maecenas volutpat",
                            StatusId = 1,
                            TraineeId = 13,
                            TrainerId = 8,
                            isDisabled = false
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 2,
                            CreatedOn = new DateTime(2022, 5, 18, 11, 42, 36, 356, DateTimeKind.Utc).AddTicks(6686),
                            Feedback = " Enim lobortis scelerisque fermentum dui faucibus in ornare quam viverra. Dui vivamus arcu felis bibendum ut. Enim blandit volutpat maecenas volutpat",
                            StatusId = 1,
                            TraineeId = 17,
                            TrainerId = 7,
                            isDisabled = false
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 1,
                            CreatedOn = new DateTime(2022, 5, 18, 11, 42, 36, 356, DateTimeKind.Utc).AddTicks(6686),
                            Feedback = "Enim lobortis scelerisque fermentum dui faucibus in ornare quam viverra. Dui vivamus arcu felis bibendum ut. Enim blandit volutpat maecenas volutpat",
                            StatusId = 1,
                            TraineeId = 12,
                            TrainerId = 8,
                            isDisabled = false
                        },
                        new
                        {
                            Id = 4,
                            CourseId = 2,
                            CreatedOn = new DateTime(2022, 5, 18, 11, 42, 36, 356, DateTimeKind.Utc).AddTicks(6686),
                            Feedback = " Enim lobortis scelerisque fermentum dui faucibus in ornare quam viverra. Dui vivamus arcu felis bibendum ut. Enim blandit volutpat maecenas volutpat",
                            StatusId = 1,
                            TraineeId = 16,
                            TrainerId = 7,
                            isDisabled = false
                        });
                });

            modelBuilder.Entity("TMS.BAL.TraineeFeedbackStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("TraineeFeedbackStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2022, 5, 18, 11, 42, 36, 356, DateTimeKind.Utc).AddTicks(6686),
                            Status = "Given"
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2022, 5, 18, 11, 42, 36, 356, DateTimeKind.Utc).AddTicks(6686),
                            Status = "Yet to be Give"
                        });
                });

            modelBuilder.Entity("TMS.BAL.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Base64")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("isDisabled")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Base64 = "data:image/jpeg;base64,",
                            CreatedOn = new DateTime(2022, 5, 18, 11, 42, 36, 356, DateTimeKind.Utc).AddTicks(6686),
                            Email = "Warren.Mackenzie@tms.edu.in",
                            EmployeeId = "TMS101",
                            FullName = "Warren Mackenzie",
                            Password = "XIBWXbbynaCwGqElIsN7MvEhy+R6hh738AbLIpIt/6E=",
                            RoleId = 1,
                            UserName = "Warren",
                            isDisabled = false
                        },
                        new
                        {
                            Id = 2,
                            Base64 = "data:image/jpeg;base64,",
                            CreatedOn = new DateTime(2022, 5, 18, 11, 42, 36, 356, DateTimeKind.Utc).AddTicks(6686),
                            Email = "William.MacLeod@tms.edu.in",
                            EmployeeId = "TMS102",
                            FullName = "William MacLeod",
                            Password = "XIBWXbbynaCwGqElIsN7MvEhy+R6hh738AbLIpIt/6E=",
                            RoleId = 1,
                            UserName = "William",
                            isDisabled = false
                        },
                        new
                        {
                            Id = 3,
                            Base64 = "data:image/jpeg;base64,",
                            CreatedOn = new DateTime(2022, 5, 18, 11, 42, 36, 356, DateTimeKind.Utc).AddTicks(6686),
                            Email = "Abigail.Manning@tms.edu.in",
                            EmployeeId = "TMS203",
                            FullName = "Abigail Manning",
                            Password = "XIBWXbbynaCwGqElIsN7MvEhy+R6hh738AbLIpIt/6E=",
                            RoleId = 2,
                            UserName = "Abigail",
                            isDisabled = false
                        },
                        new
                        {
                            Id = 4,
                            Base64 = "data:image/jpeg;base64,",
                            CreatedOn = new DateTime(2022, 5, 18, 11, 42, 36, 356, DateTimeKind.Utc).AddTicks(6686),
                            Email = "Alexandra.Marshall@tms.edu.in",
                            EmployeeId = "TMS204",
                            FullName = "Alexandra Marshall",
                            Password = "XIBWXbbynaCwGqElIsN7MvEhy+R6hh738AbLIpIt/6E=",
                            RoleId = 2,
                            UserName = "Alexandra",
                            isDisabled = false
                        },
                        new
                        {
                            Id = 5,
                            Base64 = "data:image/jpeg;base64,",
                            CreatedOn = new DateTime(2022, 5, 18, 11, 42, 36, 356, DateTimeKind.Utc).AddTicks(6686),
                            Email = "Alison.Martin@tms.edu.in",
                            EmployeeId = "TMS205",
                            FullName = "Alison Martin",
                            Password = "XIBWXbbynaCwGqElIsN7MvEhy+R6hh738AbLIpIt/6E=",
                            RoleId = 2,
                            UserName = "Alison",
                            isDisabled = false
                        },
                        new
                        {
                            Id = 6,
                            Base64 = "data:image/jpeg;base64,",
                            CreatedOn = new DateTime(2022, 5, 18, 11, 42, 36, 356, DateTimeKind.Utc).AddTicks(6686),
                            DepartmentId = 1,
                            Email = "Austin.Bailey@tms.edu.in",
                            EmployeeId = "TMS316",
                            FullName = "Austin Bailey",
                            Password = "XIBWXbbynaCwGqElIsN7MvEhy+R6hh738AbLIpIt/6E=",
                            RoleId = 3,
                            UserName = "Austin",
                            isDisabled = false
                        },
                        new
                        {
                            Id = 7,
                            Base64 = "data:image/jpeg;base64,",
                            CreatedOn = new DateTime(2022, 5, 18, 11, 42, 36, 356, DateTimeKind.Utc).AddTicks(6686),
                            DepartmentId = 2,
                            Email = "Benjamin.Baker@tms.edu.in",
                            EmployeeId = "TMS327",
                            FullName = "Benjamin Baker",
                            Password = "XIBWXbbynaCwGqElIsN7MvEhy+R6hh738AbLIpIt/6E=",
                            RoleId = 3,
                            UserName = "Benjamin",
                            isDisabled = false
                        },
                        new
                        {
                            Id = 8,
                            Base64 = "data:image/jpeg;base64,",
                            CreatedOn = new DateTime(2022, 5, 18, 11, 42, 36, 356, DateTimeKind.Utc).AddTicks(6686),
                            DepartmentId = 3,
                            Email = "Blake.Ball@tms.edu.in",
                            EmployeeId = "TMS338",
                            FullName = "Blake Ball",
                            Password = "XIBWXbbynaCwGqElIsN7MvEhy+R6hh738AbLIpIt/6E=",
                            RoleId = 3,
                            UserName = "Blake",
                            isDisabled = false
                        },
                        new
                        {
                            Id = 9,
                            Base64 = "data:image/jpeg;base64,",
                            CreatedOn = new DateTime(2022, 5, 18, 11, 42, 36, 356, DateTimeKind.Utc).AddTicks(6686),
                            DepartmentId = 1,
                            Email = "Ella.Payne@tms.edu.in",
                            EmployeeId = "TMS519",
                            FullName = "Ella Payne",
                            Password = "XIBWXbbynaCwGqElIsN7MvEhy+R6hh738AbLIpIt/6E=",
                            RoleId = 5,
                            UserName = "Ella",
                            isDisabled = false
                        },
                        new
                        {
                            Id = 10,
                            Base64 = "data:image/jpeg;base64,",
                            CreatedOn = new DateTime(2022, 5, 18, 11, 42, 36, 356, DateTimeKind.Utc).AddTicks(6686),
                            DepartmentId = 2,
                            Email = "Emily.Peake@tms.edu.in",
                            EmployeeId = "TMS5210",
                            FullName = "Emily Peake",
                            Password = "XIBWXbbynaCwGqElIsN7MvEhy+R6hh738AbLIpIt/6E=",
                            RoleId = 5,
                            UserName = "Emily",
                            isDisabled = false
                        },
                        new
                        {
                            Id = 11,
                            Base64 = "data:image/jpeg;base64,",
                            CreatedOn = new DateTime(2022, 5, 18, 11, 42, 36, 356, DateTimeKind.Utc).AddTicks(6686),
                            DepartmentId = 3,
                            Email = "Emma.Peters@tms.edu.in",
                            EmployeeId = "TMS5211",
                            FullName = "Emma Peters",
                            Password = "XIBWXbbynaCwGqElIsN7MvEhy+R6hh738AbLIpIt/6E=",
                            RoleId = 5,
                            UserName = "Emma",
                            isDisabled = false
                        },
                        new
                        {
                            Id = 12,
                            Base64 = "data:image/jpeg;base64,",
                            CreatedOn = new DateTime(2022, 5, 18, 11, 42, 36, 356, DateTimeKind.Utc).AddTicks(6686),
                            DepartmentId = 1,
                            Email = "Charles.Bower@tms.edu",
                            EmployeeId = "TMS4112",
                            FullName = "Charles Bower",
                            Password = "XIBWXbbynaCwGqElIsN7MvEhy+R6hh738AbLIpIt/6E=",
                            RoleId = 4,
                            UserName = "Charles",
                            isDisabled = false
                        },
                        new
                        {
                            Id = 13,
                            Base64 = "data:image/jpeg;base64,",
                            CreatedOn = new DateTime(2022, 5, 18, 11, 42, 36, 356, DateTimeKind.Utc).AddTicks(6686),
                            DepartmentId = 2,
                            Email = "Christian.Brown@tms.edu",
                            EmployeeId = "TMS4213",
                            FullName = "Christian Brown",
                            Password = "XIBWXbbynaCwGqElIsN7MvEhy+R6hh738AbLIpIt/6E=",
                            RoleId = 4,
                            UserName = "Christian",
                            isDisabled = false
                        },
                        new
                        {
                            Id = 14,
                            Base64 = "data:image/jpeg;base64,",
                            CreatedOn = new DateTime(2022, 5, 18, 11, 42, 36, 356, DateTimeKind.Utc).AddTicks(6686),
                            DepartmentId = 3,
                            Email = "Christopher.Buckland@tms.edu",
                            EmployeeId = "TMS4314",
                            FullName = "Christopher Buckland",
                            Password = "XIBWXbbynaCwGqElIsN7MvEhy+R6hh738AbLIpIt/6E=",
                            RoleId = 4,
                            UserName = "Christopher",
                            isDisabled = false
                        },
                        new
                        {
                            Id = 15,
                            Base64 = "data:image/jpeg;base64,",
                            CreatedOn = new DateTime(2022, 5, 18, 11, 42, 36, 356, DateTimeKind.Utc).AddTicks(6686),
                            DepartmentId = 1,
                            Email = "Gabrielle.Pullman@tms.edu.in",
                            EmployeeId = "TMS4115",
                            FullName = "Gabrielle Pullman",
                            Password = "XIBWXbbynaCwGqElIsN7MvEhy+R6hh738AbLIpIt/6E=",
                            RoleId = 4,
                            UserName = "Gabrielle",
                            isDisabled = false
                        },
                        new
                        {
                            Id = 16,
                            Base64 = "data:image/jpeg;base64,",
                            CreatedOn = new DateTime(2022, 5, 18, 11, 42, 36, 356, DateTimeKind.Utc).AddTicks(6686),
                            DepartmentId = 2,
                            Email = "Grace.Quinn@tms.edu.in",
                            EmployeeId = "TMS4216",
                            FullName = "Grace Quinn",
                            Password = "XIBWXbbynaCwGqElIsN7MvEhy+R6hh738AbLIpIt/6E=",
                            RoleId = 4,
                            UserName = "Grace",
                            isDisabled = false
                        },
                        new
                        {
                            Id = 17,
                            Base64 = "data:image/jpeg;base64,",
                            CreatedOn = new DateTime(2022, 5, 18, 11, 42, 36, 356, DateTimeKind.Utc).AddTicks(6686),
                            DepartmentId = 3,
                            Email = "Hannah.Rampling@tms.edu.in",
                            EmployeeId = "TMS4217",
                            FullName = "Hannah Rampling",
                            Password = "XIBWXbbynaCwGqElIsN7MvEhy+R6hh738AbLIpIt/6E=",
                            RoleId = 4,
                            UserName = "Hannah",
                            isDisabled = false
                        });
                });

            modelBuilder.Entity("CourseUser", b =>
                {
                    b.HasOne("TMS.BAL.Course", null)
                        .WithMany()
                        .HasForeignKey("CoursesId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TMS.BAL.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("TMS.BAL.Assignment", b =>
                {
                    b.HasOne("TMS.BAL.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TMS.BAL.AssignmentStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TMS.BAL.Topic", "Topic")
                        .WithMany("Assignments")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("Status");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("TMS.BAL.Attendance", b =>
                {
                    b.HasOne("TMS.BAL.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TMS.BAL.AttendanceStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TMS.BAL.Topic", "Topic")
                        .WithMany("Attendances")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("Status");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("TMS.BAL.Course", b =>
                {
                    b.HasOne("TMS.BAL.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TMS.BAL.CourseStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId");

                    b.Navigation("Department");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("TMS.BAL.CourseFeedback", b =>
                {
                    b.HasOne("TMS.BAL.Course", "Course")
                        .WithMany("Feedbacks")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TMS.BAL.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("TMS.BAL.MOM", b =>
                {
                    b.HasOne("TMS.BAL.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TMS.BAL.Review", "Review")
                        .WithMany()
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TMS.BAL.MOMStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("Review");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("TMS.BAL.Review", b =>
                {
                    b.HasOne("TMS.BAL.User", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TMS.BAL.ReviewStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TMS.BAL.User", "Trainee")
                        .WithMany()
                        .HasForeignKey("TraineeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Reviewer");

                    b.Navigation("Status");

                    b.Navigation("Trainee");
                });

            modelBuilder.Entity("TMS.BAL.Topic", b =>
                {
                    b.HasOne("TMS.BAL.Course", "Course")
                        .WithMany("Topics")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("TMS.BAL.TraineeFeedback", b =>
                {
                    b.HasOne("TMS.BAL.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TMS.BAL.TraineeFeedbackStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId");

                    b.HasOne("TMS.BAL.User", "Trainee")
                        .WithMany()
                        .HasForeignKey("TraineeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TMS.BAL.User", "Trainer")
                        .WithMany()
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Status");

                    b.Navigation("Trainee");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("TMS.BAL.User", b =>
                {
                    b.HasOne("TMS.BAL.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId");

                    b.HasOne("TMS.BAL.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("TMS.BAL.Course", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("Topics");
                });

            modelBuilder.Entity("TMS.BAL.Topic", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Attendances");
                });
#pragma warning restore 612, 618
        }
    }
}